### PR TITLE
[QMR] Combined Rates Measurement Page - Initial

### PR DESCRIPTION
**Pull request by ajaitasaini**
### Description

This page will display the combined rates for a QMR user that are associated with the separated or combined measures. This story only covers the initial sections (Header, Copy, Links back to the measures).

### Related ticket(s)

CMDCT-3637

---
### How to test

1. In FFY 2024, go to the "View Combined Rates" section 
2. Click into one of the measures and make sure that the layout looks correct, specifically the header and a section with h2 and two links, one that redirects to the chip coreset measure page and another to the medicaid coreset measure page. Confirm that the links are redirecting to the correct pages.  
3. The body text is a placeholder and there's a followup ticket that will address that. 

### Notes

---
### Pre-review checklist

- [x] I have added [thorough](https://shorturl.at/aejkF) tests, if necessary
- [ ] I have updated relevant documentation, if necessary
- [x] I have performed a self-review of my code
- [ ] I have manually tested this PR in the deployed cloud environment

---
#### Review
- [ ] Design: This work has been reviewed and approved by design, if necessary
- [ ] Product: This work has been reviewed and approved by product owner, if necessary

#### Security
_If either of the following are true, notify the team's ISSO (Information System Security Officer)._

- [ ] These changes are significant enough to require an update to the SIA.
- [ ] These changes are significant enough to require a penetration test.
---

_convert to a different template: [test → val](?expand=1&template=test-to-val-deployment.md)_ | _[val → prod](?expand=1&template=val-to-prod-deployment.md)_

### CODE REVIEW

**Comment by benmartin-coforma** [comment]
I like the code here, but navigating to the individual measures through the links on this page puts the app in a weird state, such that the `<` link on the breadcrumb trail doesn't work quite right.

I haven't dug into this, so I'm not sure how to explain it yet; screen recording below.

I would be surprised if this issue were related to the current work. More likely, it is an underlying issue with how QMR handles direct URL navigation. As such, it's probably out of scope here; I'm just making the note here so that we can follow up.

https://github.com/Enterprise-CMCS/macpro-mdct-qmr/assets/126210497/889fa290-2e99-46b8-9005-8dd747c41dc7

**Comment by benmartin-coforma** [comment]
Cloudfront env is here: https://d3fybpu2xevre0.cloudfront.net/

**Review by ailZhou — APPROVED** [review]
LGTM, links are being generated and being redirected correctly to the measures. Also, thanks for fixing the issue with AAB-AD! 

Question: Not a blocker, but I'm wondering why the Link to Medicaid has a class tag but CHIP doesn't?

**Review by keeysnc — APPROVED** [review]

**Comment by ajaitasaini** [comment]
@ailZhou good question r/e class tag! that's some leftover code that I will get rid of in a follow up PR for this component

**Pull request merged**
