### PR TITLE
Child and HH Banner Link

### PR DESCRIPTION
**Pull request by ailZhou**
### Description

The Child banner and HH banner needs to have a link added to the text.

HH is linked to this pdf
https://www.medicaid.gov/sites/default/files/2024-03/smd24002.pdf

Child is linked to this pdf
https://www.medicaid.gov/sites/default/files/2023-12/sho23005_1.pdf

### Related ticket(s)

CMDCT-3920

---
### How to test

Deploy Link: https://d1qqmduypn9ig7.cloudfront.net/

1) Sign into QMR, [stateuserWA@test.com](mailto:stateuserDC@test.com).
2) Add a Health Home CoreSet.
3) Go to the Health Home CoreSet measure list and see that there's a link and the link opens in a new tab.
Screenshot 2024-08-19 at 1 24 16 PM

4) Do the same for Child CoreSet measure list and see that there's a link and the link opens in a new tab.
Screenshot 2024-08-19 at 1 24 02 PM

### Notes

---
### Pre-review checklist

- [ ] I have added [thorough](https://shorturl.at/aejkF) tests, if necessary
- [ ] I have updated relevant documentation, if necessary
- [ ] I have performed a self-review of my code
- [ ] I have manually tested this PR in the deployed cloud environment

---
#### Review
- [ ] Design: This work has been reviewed and approved by design, if necessary
- [ ] Product: This work has been reviewed and approved by product owner, if necessary

#### Security
_If either of the following are true, notify the team's ISSO (Information System Security Officer)._

- [ ] These changes are significant enough to require an update to the SIA.
- [ ] These changes are significant enough to require a penetration test.
---

_convert to a different template: [test → val](?expand=1&template=test-to-val-deployment.md)_ | _[val → prod](?expand=1&template=val-to-prod-deployment.md)_

### CODE REVIEW

**Review by rocio-desantiago — COMMENTED** [review]
Link works as expected. Only concern is that visually it's hard to see the link. Could we make it appear underlined?

> For accessibility purposes, it's suggested to underline hyperlinks, for those who are color blind or have cognitive disabilities.

**Comment by ailZhou** [comment]
> Link works as expected. Only concern is that visually it's hard to see the link. Could we make it appear underlined?
> 
> > For accessibility purposes, it's suggested to underline hyperlinks, for those who are color blind or have cognitive disabilities.

this might be something we want to make a separate ticket for as all our links are structured without an underline and may want to standardize it to a specific styling, or at least talk to design & product to see what they think of it.

**Review by rocio-desantiago — APPROVED** [review]

**Comment by rocio-desantiago** [comment]
> > Link works as expected. Only concern is that visually it's hard to see the link. Could we make it appear underlined?
> > > For accessibility purposes, it's suggested to underline hyperlinks, for those who are color blind or have cognitive disabilities.
> 
> @rocio-desantiago this might be something we want to make a separate ticket for as most of our links are structured without an underline and may want to standardize it to a specific styling, or at least talk to design & product to see what they think of it.

Sounds good. I'll write a ticket to follow up on this 😄

**Review by BearHanded — APPROVED** [review]

**Review by ajaitasaini — APPROVED** [review]
lgtm! tested in cloudfront

**Pull request merged**
