### PR TITLE
QMR - Qualifier Questions Content Updates - Part 2

### PR DESCRIPTION
**Pull request by rocio-desantiago**
### Description
Content updates made to Qualifier portion of measures
- "title" capitalized
- "(Title XIX & XXI)" added to "Medicaid" titles
- lowecase "Separate"
- Column "Age 65 and older" removed from Adult Core Set Qualifiers: CHIP
- "Separate Chip" added to "Ages 21 to 64" column
- **For MCHIP states:**
   -  **_Adult Core Set Qualifiers:_** "MEDICAID (TITLE XIX & XXI)" added to both age group columns
   -  **_Child Core Set Qualifiers:_** "(TITLE XIX & XXI)" added to Medicaid column

### Related ticket(s)

CMDCT-3902

---
### How to test
Upon selecting the Core Set Name from the Home Page with stateuser1@test.com
**The changes are in the following Core Set Qualifiers:**
1. Child Core Set Measures: Medicaid (Title XIX & XXI)
2. Child Core Set Measures: Separate CHIP
3. Adult Core Set Measures: Medicaid (Title XIX & XXI)
4. Adult Core Set Measures: Separate CHIP

**Core sets available for MCHIP states with internaluser@test.com:**
_Alaska, American Samoa, DC, Guam, Hawaii, New Hampshire, New Mexico, North Carolina, North Dakota, Northern Mariana Islands, Ohio, Puerto Rico, South Carolina, US Virgin Islands, Vermont & Wyoming_

1. Child Core Set Measures: Medicaid (Title XIX & XXI)
2. Adult Core Set Measures: Medicaid (Title XIX & XXI)

### Example with selecting _Child Core Set Measures: Medicaid (Title XIX & XXI)_
Sign in with internaluser@test.com and select any state to see changes in the following core sets:
Core Sets on MCHIP state 

Sign in with stateuser1@test.com to see changes in the following core sets:
Core Sets on separate CHIP states 

Upon selecting a Coreset, select the top link right above the list of measures on the following page.
Core Set Qualifiers 

### Notes
**See comments below for before and after of content changes**

---
### Pre-review checklist

- [ ] I have added [thorough](https://shorturl.at/aejkF) tests, if necessary
- [ ] I have updated relevant documentation, if necessary
- [x] I have performed a self-review of my code
- [ ] I have manually tested this PR in the deployed cloud environment

---
#### Review
- [ ] Design: This work has been reviewed and approved by design, if necessary
- [ ] Product: This work has been reviewed and approved by product owner, if necessary

### CODE REVIEW

**Comment by rocio-desantiago** [comment]
For MCHIP States: 
| Adult Core Set Qualifiers - MCHIP state - Before |
| ----- |
| AdultCoreSetQualifiers_MCHIP-State_BEFORE |

| After (column titles added) |
| ----- |
| AdultCoreSetQualifiers_MCHIP-State |

| Child Core Set Qualifiers: Medicaid & Chip - MCHIP state - Before |
| ----- |
| ChildCoreSetQualifiers_Alaska_BEFORE |

| After (Medicaid column titles added) |
| ----- |
| ChildCoreSetQualifiers_MCHIP-State |

**Comment by rocio-desantiago** [comment]
For Medicaid & Separate CHIP states (stateuser1@test.com)
These are the following changes
| Child Core Set Qualifiers: Medicaid - Before |
| ------ |
| ChildCoreSetQualifiersMedicaid_BEFORE  | 

| After (Capitalize Title and add subtitle) |
| ------ |
| ChildCoreSetQualifiersMedicaid  |

| Child Core Set Qualifiers: CHIP - Before |
| ------ |
| ChildCoreSet_SeparateCHIP_BEFORE  | 

| After (undercase separate and add Separate to Column title) |
| ------ |
| ChildCoresSet_SeparateCHIP  |

| Adult Core Set Qualifiers: Medicaid - Before |
| ------ |
| AdultCoreSetMedicaid_BEFORE  | 

| After (capitalize Title and add "Medicaid (Title XIX & XXI)" to Column title) |
| ------ |
| AdultCoreSetMedicaid  |

**Comment by rocio-desantiago** [comment]
For Medicaid & Separate CHIP states (stateuser1@test.com)
These are the following changes for Adult Core Sets

**Review by ajaitasaini — DISMISSED** [review]
tested via cloudfront + approving because the content changes seem to match testing instructions, would recommend getting DK's approval before merging in case there's any subtleties that were missed!

**Comment by rocio-desantiago** [comment]
Must apply changes to HH 
"This will cover updates to the Qualifier Questions for Child, Adult and HH."

**Comment by rocio-desantiago** [comment]
To confirm if these are the correct updates for Home Health
Screenshot 2024-08-12 at 3 52 51 PM

**Review by BearHanded — APPROVED** [review]

**Review by BearHanded — APPROVED** [review]

**Review by ajaitasaini — APPROVED** [review]

**Review by benmartin-coforma — APPROVED** [review]

**Pull request merged**
